# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Collect Baekjoon Group Data

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Collect Baekjoon Group Data
      env:
        GROUP_ID: 12455
        BOJ_AUTO_LOGIN: ${{ secrets.BOJ_AUTO_LOGIN }}
        ONLINE_JUDGE: ${{ secrets.ONLINE_JUDGE }}
      run: |
        python main.py
    - name: Commit
      run: |
        git config --local user.email "dalgors.deu@gmail.com"
        git config --local user.name "dalgors"
        git add .
        if [ -z "$(git status --porcelain)" ]; then echo "Nothing changed"; else git commit -m "[Bot] Update files"; fi
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        branch: 'main'
        github_token: $
